name: wagl
channels:
  - conda-forge/label/dev
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - luigi >= 2.4.0
  - numpy = 1.13.*
  - scipy >= 0.14
  - numexpr >= 2.4.6
  - ephem >= 3.7.5.3
  - pyproj > 1.9.5
  - scikit-image >= 0.8.2
  - GDAL >= 1.9.2,!=2.1.4 # 2.1.4 throws an error when importing version 2018-01-24 (conda-forge)
  - rasterio >= 0.9 # 0.9 gets around 1.0a ordering problems
  - fiona >= 1.7.0
  - shapely >= 1.5.13
  - h5py >= 2.5.0
  - pandas >= 0.17.1
  - geopandas >= 0.1.1
  - pyyaml=5.1.2
  - python-dateutil >= 2.6.1
  - pip:
    - tables >= 3.4.2
    - nested_lookup >= 0.1.3
    - structlog >= 16.1.0
    - git+git://github.com/sixy6e/idl-functions.git@master
